# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build Example

on:
  push:
    branches: [ main]
jobs:

  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Step 3 - Build Maven Project
        run: mvn --batch-mode -DskipTests package

      - name: Step 4 - run test cases
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Step 5- Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true 


          
          
          
